defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

run_mode: train
jit: false

scheduler:
  decay_rate: 0.95
  decay_steps: 15000

training:
  rec_results_freq : 10000
  rec_constraint_freq: 50000
  max_steps : 300000


batch_size:
  initial_condition: 4096
  inlet: 1100
  outlet: 650
  no_slip: 5200
  interior: 6000
  integral_continuity: 310